# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuey', '0002_auto_20160601_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
